#! /bin/tcsh -f

#-- define package/DB versions
set DAVINCI_VERSION = v37r2p4

#-- Directory and files
set GENERAL_LOG = general.log

#-- basic info
set DATE = `date`
cat -<<EOF> ${GENERAL_LOG}
====================================================
START@:     ${DATE}
====================================================
EOF

#-- setup LHCb environment
setenv CMTCONFIG x86_64-slc6-gcc48-opt
source /cvmfs/lhcb.cern.ch/group_login.csh >>& ${GENERAL_LOG}

#-- DaVinci

echo "======================= DaVinci script ========================" >> ${GENERAL_LOG}
cat Xb2JpsiLKMC.py >> ${GENERAL_LOG}
echo "======================= DaVinci script (Xb2JpsiXTreeMC.py) ====" >> ${GENERAL_LOG}
cat Xb2JpsiXTreeMC.py >> ${GENERAL_LOG}

SetupProject DaVinci ${DAVINCI_VERSION} >>& ${GENERAL_LOG}

foreach YEAR (11 12)
foreach POLARITY (Down Up)
if (${YEAR} == 11) then
set BEAM = 3500
set STRIP = 20r1
else
if (${YEAR} == 12) then
set BEAM = 4000
set STRIP = 20
endif
endif

set DAVINCI_LOG = davinci_${YEAR}_${POLARITY}.log

cat -<<EOF> myDaVinci_TupleFile.py
from Configurables import DaVinci
DaVinci().TupleFile = "DVNtuples_${YEAR}_${POLARITY}.root"

EOF

#-- basic info
set DATE = `date`
cat -<<EOF> ${DAVINCI_LOG}
====================================================
START@:     ${DATE}
YEAR:       ${YEAR}
POLARITY:   ${POLARITY}
====================================================
EOF

gaudirun.py DataXb2JpsiLK.py myDaVinci_TupleFile.py LHCb_Collision${YEAR}_Beam${BEAM}GeVVeloClosedMag${POLARITY}_RealData_Reco14_Stripping${STRIP}_90000000_DIMUON.DST.py pool_${YEAR}_${POLARITY}.py >>& ${DAVINCI_LOG}

set DATE = `date`
cat -<<EOF> ${DAVINCI_LOG}
====================================================
Finish@:    ${DATE}
====================================================
EOF

rm myDaVinci_TupleFile.py

end
end

set DATE = `date`
cat -<<EOF>> ${GENERAL_LOG}
====================================================
Finish Davinci@:    ${DATE}
====================================================
EOF

ls -l >> ${GENERAL_LOG}
