#! /bin/tcsh -f

#-- define package/DB versions
set DAVINCI_VERSION = v37r2p4

#-- Directory and files
set GENERAL_LOG = general.log

#-- basic info
set DATE = `date`
cat -<<EOF> ${GENERAL_LOG}
====================================================
START@:     ${DATE}
====================================================
EOF

#-- setup LHCb environment
setenv CMTCONFIG x86_64-slc6-gcc48-opt
source /cvmfs/lhcb.cern.ch/group_login.csh >>& ${GENERAL_LOG}

#-- DaVinci

echo "======================= DaVinci script ========================" >> ${GENERAL_LOG}
cat Xb2JpsiLKMC.py >> ${GENERAL_LOG}
echo "======================= DaVinci script (Xb2JpsiXTreeMC.py) ====" >> ${GENERAL_LOG}
cat Xb2JpsiXTreeMC.py >> ${GENERAL_LOG}

SetupProject DaVinci ${DAVINCI_VERSION} >>& ${GENERAL_LOG}

foreach YEAR (2011 2012)
foreach POLARITY (Down Up)
if (${YEAR} == 2011) then
set BEAM = 3500
set NU = 2
set TCK = 0x40760037
set STRIP = 20r1
else
if (${YEAR} == 2012) then
set BEAM = 4000
set NU = 2.5
set TCK = 0x409f0045
set STRIP = 20
endif
endif

set DAVINCI_LOG = davinci_${YEAR}_${POLARITY}.log

cat -<<EOF> myDaVinci_TupleFile.py
from Configurables import DaVinci
DaVinci().TupleFile = "DVNtuples_${YEAR}_${POLARITY}.root"

EOF

#-- basic info
set DATE = `date`
cat -<<EOF> ${DAVINCI_LOG}
====================================================
START@:     ${DATE}
YEAR:       ${YEAR}
POLARITY:   ${POLARITY}
====================================================
EOF

gaudirun.py Xb2JpsiLKMC.py myDaVinci_TupleFile.py MC_${YEAR}_Beam${BEAM}GeV${YEAR}Mag${POLARITY}Nu${NU}Pythia6_Sim08a_Digi13_Trig${TCK}_Reco14a_Stripping${STRIP}NoPrescalingFlagged_15144103_ALLSTREAMS.DST.py pool_xml_catalog_${YEAR}_${POLARITY}.py >>& ${DAVINCI_LOG}

set DATE = `date`
cat -<<EOF> ${DAVINCI_LOG}
====================================================
Finish@:    ${DATE}
====================================================
EOF

rm myDaVinci_TupleFile.py

end
end

set DATE = `date`
cat -<<EOF>> ${GENERAL_LOG}
====================================================
Finish Davinci@:    ${DATE}
====================================================
EOF

ls -l >> ${GENERAL_LOG}
