#! /bin/tcsh -f

#-- Directory and files
set GENERAL_LOG = make_pool.log

#-- basic info
set DATE = `date`
cat -<<EOF> ${GENERAL_LOG}
====================================================
START@:     ${DATE}
====================================================
EOF

#-- setup LHCb environment
setenv CMTCONFIG x86_64-slc6-gcc48-opt
source /cvmfs/lhcb.cern.ch/group_login.csh >>& ${GENERAL_LOG}

#-- LHCb Dirac

SetupProject LHCbDirac >>& ${GENERAL_LOG}

foreach YEAR (11 12)
foreach POLARITY (Down Up)
if (${YEAR} == 11) then
set BEAM = 3500
set STRIP = 20r1
else
if (${YEAR} == 12) then
set BEAM = 4000
set STRIP = 20
endif
endif

set DIRAC_LOG = LHCbDirac_${YEAR}_${POLARITY}.log

#-- basic info
set DATE = `date`
cat -<<EOF> ${DIRAC_LOG}
====================================================
START@:     ${DATE}
YEAR:       ${YEAR}
POLARITY:   ${POLARITY}
====================================================
EOF

dirac-bookkeeping-genXMLCatalog --File=LHCb_Collision${YEAR}_Beam${BEAM}GeVVeloClosedMag${POLARITY}_RealData_Reco14_Stripping${STRIP}_90000000_DIMUON.DST.py --Catalog=pool_${YEAR}_${POLARITY} >>& ${DIRAC_LOG}

set DATE = `date`
cat -<<EOF> ${DIRAC_LOG}
====================================================
Finish@:    ${DATE}
====================================================
EOF

end
end

set DATE = `date`
cat -<<EOF>> ${GENERAL_LOG}
====================================================
Finish Davinci@:    ${DATE}
====================================================
EOF

ls -l >> ${GENERAL_LOG}
